name: Build Orchestrator

on:
  workflow_dispatch:
    inputs:
      tracy_tag:
        description: 'Tracy tag to build'
        required: true
        type: string

jobs:
  setup-build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout builder repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
      
      - name: Run prepare-build script
        env:
          PYTHONUNBUFFERED: 1
        run: |
          uv run prepare-build.py "${{ inputs.tracy_tag }}"
          sleep 25

      - name: Dispatch build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-combined.yml
          ref: build-${{ inputs.tracy_tag }}
          token: ${{ steps.generate-token.outputs.token }}
          inputs: '{"tracy_tag": "${{ inputs.tracy_tag }}"}'